config/routes.rb
Rails.application.routes.draw do
  get '/', :to => redirect('/casos')
  get '/alumnos/:id/casos', :to => 'alumnos#casos'
  get '/caso/:id/alumno/new', :to => 'alumnos#new'
  resources :faltas
  resources :contravenciones
  resources :sanciones
  resources :documentos
  resources :seguimientos
  resources :castigos
  resources :involucrados
  resources :casos do
    resources :involucrados
  end
  resources :casos do
    resources :involucrados do
      resources :contravenciones
    end
  end
  resources :casos do
    resources :involucrados do
      resources :castigos
    end
  end
  resources :casos do
    resources :seguimientos do
      resources :documentos
    end
  end
  resources :alumnos
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/alumno.rb
class Alumno < ApplicationRecord
  validates :nombre, :presence => true
  validates :rude, :presence => true
  validates :ci, :presence => true
  validates_uniqueness_of :rude, :message => "ya pertenece a otro alumno"
  validates_uniqueness_of :ci, :message => "ya pertenece a otro alumno"
end

app/controllers/alumnos_controller.rb
class AlumnosController < ApplicationController
  before_action :set_alumno, only: %i[ show edit update destroy casos]
  #before_action :get_caso, only: %i[ new ]

  # GET /alumnos or /alumnos.json
  def index
    @alumnos = Alumno.all
  end

  def casos
    @casos = Caso.where(id: Involucrado.select("caso_id").where(alumno_id: params[:id]))
  end

  # GET /alumnos/1 or /alumnos/1.json
  def show
  end

  # GET /alumnos/new
  def new
    @alumno = Alumno.new
    @alumno.caso__id = params[:id]
  end

  # GET /alumnos/1/edit
  def edit
  end

  # POST /alumnos or /alumnos.json
  def create    
    @alumno = Alumno.new(alumno_params)    
    respond_to do |format|
      if @alumno.save
        format.html { redirect_to new_caso_involucrado_path(@alumno.caso__id), notice: "Alumno creado." }
        format.json { render :show, status: :created, location: @alumno }
      else
        format.html { render :new, status: :unprocessable_entity }        
        #format.html { redirect_to new_caso_alumno_path(caso__id), notice: "Error" }
        format.json { render json: @alumno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alumnos/1 or /alumnos/1.json
  def update
    respond_to do |format|
      if @alumno.update(alumno_params)
        format.html { redirect_to @alumno, notice: "Alumno modificado." }
        format.json { render :show, status: :ok, location: @alumno }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @alumno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alumnos/1 or /alumnos/1.json
  def destroy
    begin
      @alumno.destroy
    rescue ActiveRecord::InvalidForeignKey => e
      respond_to do |format|
        format.html { redirect_to alumnos_url, notice: "No puede borrar el alumno hasta no haber borrado sus casos." }
        format.json { head :no_content }
      end
      return
    end
    respond_to do |format|
      format.html { redirect_to alumnos_url, notice: "Alumno borrado." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alumno
      @alumno = Alumno.find(params[:id])
    end

    def get_caso
      @caso = Caso.find(params[:caso_id])
    end

    # Only allow a list of trusted parameters through.
    def alumno_params
      params.require(:alumno).permit(:nombre, :rude, :ci, :caso__id)
    end
end

app/helpers/alumnos_helper.rb
module AlumnosHelper
end

app/views/alumnos/_form.html.erb
<%= form_with(model: alumno) do |form| %>
  <% if alumno.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(alumno.errors.count, "errores") %> evitaron que este alumno fuera grabado:</h2>

      <ul>
        <% alumno.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.text_field :caso__id, :hidden => true %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :rude %>
    <%= form.text_field :rude %>
  </div>

  <div class="field">
    <%= form.label :ci %>
    <%= form.text_field :ci %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/alumnos/casos.html.erb
<h1>Casos Alumno <%= @alumno.nombre %></h1>

<table>
  <thead>
    <tr>
      <th>Fecha</th>
      <th>Estado</th>
      <th>Denunciante</th>
      <th>Descripcion</th>
      <th>Responsable</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @casos.each do |caso| %>
      <tr>
        <td><%= caso.fecha.localtime.strftime("%d/%m/%Y %H:%M") %></td>
        <td><%= caso.estado %></td>
        <td><%= caso.denunciante %></td>
        <td><%= caso.descripcion %></td>
        <td><%= caso.responsable %></td>
        <td><%= link_to 'Ver', caso, :class => "button" %></td>
        <td><%= link_to 'Modificar', edit_caso_path(caso), :class => "button" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Volver', alumnos_path, :class => "button" %>

app/views/alumnos/edit.html.erb
<h1>Editing Alumno</h1>

<%= render 'form', alumno: @alumno %>

<%= link_to 'Show', @alumno, :class => "button" %> |
<%= link_to 'Back', alumnos_path, :class => "button" %>

app/views/alumnos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Alumnos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Rude</th>
      <th>Ci</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alumnos.each do |alumno| %>
      <tr>
        <td><%= alumno.nombre %></td>
        <td><%= alumno.rude %></td>
        <td><%= alumno.ci %></td>
        <td><%= link_to 'Casos', "/alumnos/" + alumno.id.to_s + "/casos", :class => "button" %></td>
        <td><%= link_to 'Modificar', edit_alumno_path(alumno), :class => "button" %></td>
        <td><%= link_to 'Borrar', alumno, method: :delete, data: { confirm: '¿Esta seguro?' }, :class => "button" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/alumnos/new.html.erb
<h1>Nuevo Alumno</h1>

<%= render 'form', alumno: @alumno %>

<%= link_to 'Volver', :back, :class => "button" %>

app/views/alumnos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @alumno.nombre %>
</p>

<p>
  <strong>Rude:</strong>
  <%= @alumno.rude %>
</p>

<p>
  <strong>Ci:</strong>
  <%= @alumno.ci %>
</p>

<%= link_to 'Edit', edit_alumno_path(@alumno), :class => "button" %> |
<%= link_to 'Back', alumnos_path, :class => "button" %>