config/routes.rb
Rails.application.routes.draw do
  get '/', :to => redirect('/casos')
  get '/alumnos/:id/casos', :to => 'alumnos#casos'
  get '/caso/:id/alumno/new', :to => 'alumnos#new'
  resources :faltas
  resources :contravenciones
  resources :sanciones
  resources :documentos
  resources :seguimientos
  resources :castigos
  resources :involucrados
  resources :casos do
    resources :involucrados
  end
  resources :casos do
    resources :involucrados do
      resources :contravenciones
    end
  end
  resources :casos do
    resources :involucrados do
      resources :castigos
    end
  end
  resources :casos do
    resources :seguimientos do
      resources :documentos
    end
  end
  resources :alumnos
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/involucrado.rb
class Involucrado < ApplicationRecord
  belongs_to :caso
  belongs_to :alumno
  validates :participacion, :presence => true
  validates_uniqueness_of :alumno_id, scope: :caso_id, :message => "ya está involucrado en el caso"
end

app/controllers/involucrados_controller.rb
class InvolucradosController < ApplicationController
  before_action :get_caso, only: %i[ index ]
  before_action :set_involucrado, only: %i[ show edit update destroy ]

  # GET /involucrados or /involucrados.json
  def index
    @involucrados = Involucrado.all
  end

  # GET /involucrados/1 or /involucrados/1.json
  def show
    @contravenciones = Contravencion.where(["caso_id=? and involucrado_id=?", @involucrado.caso_id, @involucrado.id])
    @castigos = Castigo.where(["caso_id=? and involucrado_id=?", @involucrado.caso_id, @involucrado.id])
    @alumno = Alumno.find(@involucrado.alumno_id)
  end

  # GET /involucrados/new
  def new
    @involucrado = Involucrado.new
    @alumnos = Alumno.all
    @involucrado.fecha = Time.now
    @involucrado.estado = "Vigente"
    @involucrado.caso_id = params[:caso_id]
    @enlace = "/caso/#{@involucrado.caso.id}/alumno/new"
  end

  # GET /involucrados/1/edit
  def edit
    @alumnos = Alumno.all
    @enlace = "/caso/#{@involucrado.caso.id}/alumno/new"
  end

  # POST /involucrados or /involucrados.json
  def create
    @involucrado = Involucrado.new(involucrado_params)
    respond_to do |format|
      if @involucrado.save
        format.html { redirect_to @involucrado.caso, notice: "Involucrado creado." }
        format.json { render :show, status: :created, location: @involucrado }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @involucrado.errors, status: :unprocessable_entity }
      end  
    end
  end

  # PATCH/PUT /involucrados/1 or /involucrados/1.json
  def update
    respond_to do |format|
      if @involucrado.update!(involucrado_params)
        #format.html { redirect_to @involucrado, notice: "Involucrado actualizado." }
        format.html { redirect_to @involucrado.caso, notice: "Involucrado actualizado." }
        format.json { render :show, status: :ok, location: @involucrado }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @involucrado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /involucrados/1 or /involucrados/1.json
  def destroy
    begin
      @involucrado.destroy
    rescue ActiveRecord::InvalidForeignKey => e
      respond_to do |format|
        format.html { redirect_to @involucrado.caso, notice: "No puede borrar el involucrado hasta no eliminar sus contravenciones y castigos." }
        format.json { head :no_content }
      end
      return
    end
    respond_to do |format|
      format.html { redirect_to @involucrado.caso, notice: "Involucrado borrado." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_involucrado
    @involucrado = Involucrado.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def involucrado_params
    params.require(:involucrado).permit(:fecha, :estado, :caso_id, :alumno_id, :participacion)
  end

  def get_caso
    @caso = Caso.find(params[:caso_id])
  end
end

app/helpers/involucrados_helper.rb
module InvolucradosHelper
end

app/views/involucrados/_form.html.erb
<%= form_with(model: involucrado) do |form| %>
  <% if involucrado.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(involucrado.errors.count, "errores") %> evitaron que este involucrado fuera grabado:</h2>

      <ul>
        <% involucrado.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :fecha %>
    <%= form.text_field :fecha, :hidden => true %>
    <input value="<%= @involucrado.fecha.localtime.strftime("%d/%m/%Y %H:%M") %>" readonly>
  </div>

  <div class="field">
    <%= form.label :estado %>
    <%= form.text_field :estado, :readonly => true %>
  </div>

  <div class="field">
    <%= form.label :caso_id %>
    <%= form.text_field :caso_id, :readonly => true %>
  </div>

  <div class="field">
    <%= form.label :alumno_id %>
    <%= form.collection_select :alumno_id, Alumno.all, :id, :nombre %>
    <%= link_to 'Agregar nuevo alumno', @enlace, :class => "button" %>
  </div>

  <div class="field">
    <%= form.label :participacion %>
    <%= form.text_area :participacion %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/involucrados/edit.html.erb
<h1>Modificando Involucrado</h1>

<%= render 'form', involucrado: @involucrado %>

<%= link_to 'Ver', @involucrado, :class => "button" %> |
<%= link_to 'Volver', @involucrado.caso, :class => "button" %>

app/views/involucrados/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Involucrados</h1>

<table>
  <thead>
    <tr>
      <th>Fecha</th>
      <th>Estado</th>
      <th>Caso</th>
      <th>Alumno</th>
      <th>Participacion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @involucrados.each do |involucrado| %>
      <tr>
        <td><%= involucrado.fecha.localtime.strftime("%d/%m/%Y %H:%M") %></td>
        <td><%= involucrado.estado %></td>
        <td><%= involucrado.caso_id %></td>
        <td><%= involucrado.alumno_id %></td>
        <td><%= involucrado.participacion %></td>
        <td><%= link_to 'Show', involucrado, :class => "button" %></td>
        <td><%= link_to 'Edit', edit_involucrado_path(involucrado), :class => "button" %></td>
        <td><%= link_to 'Destroy', involucrado, method: :delete, data: { confirm: 'Are you sure?' }, :class => "button" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Estudiante Involucrado', new_caso_involucrado_path(@caso), :class => "button" %>

app/views/involucrados/new.html.erb
<h1>Nuevo Estudiante Involucrado</h1>

<%= render 'form', involucrado: @involucrado %>

<%= link_to 'Volver', @involucrado.caso, :class => "button" %>

app/views/involucrados/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fecha:</strong>
  <%= @involucrado.fecha.localtime.strftime("%d/%m/%Y %H:%M") %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @involucrado.estado %>
</p>

<p>
  <strong>Caso:</strong>
  <%= @involucrado.caso_id %>
</p>

<p>
  <strong>Alumno:</strong>
  <%= @alumno.nombre %>
</p>

<p>
  <strong>Participacion:</strong>
  <%= @involucrado.participacion %>
</p>

<p>
  <strong>Contravenciones encontradas:</strong>
  <% if @contravenciones.empty? %>
    <p>No hay contravenciones registradas aún</p>
  <% else %>
  <table>
  <thead>
  <tr>
  <th>Nro.</th>
  <th>Descripción</th>
  <th colspan="3"></th>
  </tr>
  </thead>
  <tbody>
  <% @contravenciones.each do |contravencion|%>
  <tr>
  <td><%= contravencion.id %></td>
  <td><%= contravencion.descripcion %></td>
  <td><%= link_to 'Ver', contravencion, :class => "button" %></td>
  <td><%= link_to 'Editar', edit_contravencion_path(contravencion), :class => "button" %></td>
  <td><%= link_to 'Borrar', contravencion, method: :delete, data: { confirm: '¿Esta seguro?' }, :class => "button" %></td>
  <tr>
  <% end %>
  </tbody>
  </table>
  <% end %>
  <%= link_to 'Agregar contravencion', new_caso_involucrado_contravencion_path(@involucrado.caso_id, @involucrado), :class => "button" %>  
</p>
<p>
  <strong>Castigos aplicados:</strong>
  <% if @castigos.empty? %>
    <p>No se han aplicado castigos aún</p>
  <% else %>
  <table>
  <thead>  
  <tr>
  <th>Nro.</th>
  <th>Fecha</th>
  <th>Descripción</th>
  <th>Estado</th>
  <th colspan="3"></th>
  </tr>
  </thead>
  <tbody>
  <% @castigos.each do |castigo|%>
  <tr>
  <td><%= castigo.id %></td>
  <td><%= castigo.fecha.localtime.strftime("%d/%m/%Y %H:%M") %></td>
  <td><%= castigo.descripcion %></td>
  <td><%= castigo.estado %></td>
  <td><%= link_to 'Ver', castigo, :class => "button" %></td>
  <td><%= link_to 'Editar', edit_castigo_path(castigo), :class => "button" %></td>
  <td><%= link_to 'Borrar', castigo, method: :delete, data: { confirm: '¿Esta seguro?' } %></td>
  </tr>
  <% end %>
  </tbody>
  </table>
  <% end %>  
  <%= link_to 'Agregar castigo', new_caso_involucrado_castigo_path(@involucrado.caso_id, @involucrado), :class => "button" %>
</p>

<%= link_to 'Modificar involucrado', edit_involucrado_path(@involucrado), :class => "button" %> |
<%= link_to 'Volver caso', caso_path(@involucrado.caso_id), :class => "button" %>