config/routes.rb
Rails.application.routes.draw do
  get '/', :to => redirect('/casos')
  get '/alumnos/:id/casos', :to => 'alumnos#casos'
  get '/caso/:id/alumno/new', :to => 'alumnos#new'
  resources :faltas
  resources :contravenciones
  resources :sanciones
  resources :documentos
  resources :seguimientos
  resources :castigos
  resources :involucrados
  resources :casos do
    resources :involucrados
  end
  resources :casos do
    resources :involucrados do
      resources :contravenciones
    end
  end
  resources :casos do
    resources :involucrados do
      resources :castigos
    end
  end
  resources :casos do
    resources :seguimientos do
      resources :documentos
    end
  end
  resources :alumnos
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/seguimiento.rb
class Seguimiento < ApplicationRecord
  belongs_to :caso
  validates :glosa, :presence => true
end

app/controllers/seguimientos_controller.rb
class SeguimientosController < ApplicationController
  before_action :get_caso, only: %i[ index ]
  before_action :set_seguimiento, only: %i[ show edit update destroy ]

  # GET /seguimientos or /seguimientos.json
  def index
    @seguimientos = Seguimiento.all
  end

  # GET /seguimientos/1 or /seguimientos/1.json
  def show
    @documentos = Documento.where(["seguimiento_id = ?", @seguimiento.id])
  end

  # GET /seguimientos/new
  def new
    @seguimiento = Seguimiento.new
    @seguimiento.fecha = Time.now
    @seguimiento.caso_id = params[:caso_id]
  end

  # GET /seguimientos/1/edit
  def edit
  end

  # POST /seguimientos or /seguimientos.json
  def create
    @seguimiento = Seguimiento.new(seguimiento_params)

    respond_to do |format|
      if @seguimiento.save
        format.html { redirect_to @seguimiento.caso, notice: "Seguimiento creado." }
        format.json { render :show, status: :created, location: @seguimiento }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @seguimiento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /seguimientos/1 or /seguimientos/1.json
  def update
    respond_to do |format|
      if @seguimiento.update(seguimiento_params)
        format.html { redirect_to @seguimiento.caso, notice: "Seguimiento actualizado." }
        format.json { render :show, status: :ok, location: @seguimiento }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @seguimiento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seguimientos/1 or /seguimientos/1.json
  def destroy
    begin
      @seguimiento.destroy
    rescue ActiveRecord::InvalidForeignKey => e
      respond_to do |format|
        format.html { redirect_to @seguimiento.caso, notice: "No se puede borrar el seguimiento hasta no eliminar sus documentos." }
        format.json { head :no_content }
      end
      return
    end  
    respond_to do |format|
      format.html { redirect_to @seguimiento.caso, notice: "Seguimiento borrado." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_seguimiento
      @seguimiento = Seguimiento.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def seguimiento_params
      params.require(:seguimiento).permit(:fecha, :caso_id, :numero, :glosa)
    end

    def get_caso
      @caso = Caso.find(params[:caso_id])
    end
end

app/helpers/seguimientos_helper.rb
module SeguimientosHelper
end

app/views/seguimientos/_form.html.erb
<%= form_with(model: seguimiento) do |form| %>
  <% if seguimiento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(seguimiento.errors.count, "errores") %>evitaron que este seguimiento fuera grabado:</h2>

      <ul>
        <% seguimiento.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :fecha %>
    <%- fecha_string = form.object.fecha && form.object.fecha.localtime.strftime("%d/%m/%Y %H:%M") %>
    <%= form.text_field :fecha, :value => fecha_string, :readonly => true %>
  </div>

  <div class="field">
    <%= form.label :caso_id %>
    <%= form.text_field :caso_id, :readonly => true %>
  </div>

  <div class="field">
    <%= form.label :glosa %>
    <%= form.text_area :glosa %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/seguimientos/edit.html.erb
<h1>Modificando Seguimiento</h1>

<%= render 'form', seguimiento: @seguimiento %>

<%= link_to 'Volver', @seguimiento.caso, :class => "button" %>

app/views/seguimientos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Seguimientos</h1>

<table>
  <thead>
    <tr>
      <th>Fecha</th>
      <th>Caso</th>
      <th>Numero</th>
      <th>Glosa</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @seguimientos.each do |seguimiento| %>
      <tr>
        <td><%= seguimiento.fecha.localtime.strftime("%d/%m/%Y %H:%M") %></td>
        <td><%= seguimiento.caso_id %></td>
        <td><%= seguimiento.numero %></td>
        <td><%= seguimiento.glosa %></td>
        <td><%= link_to 'Ver', seguimiento, :class => "button" %></td>
        <td><%= link_to 'Modificar', edit_seguimiento_path(seguimiento), :class => "button" %></td>
        <td><%= link_to 'Borrar', seguimiento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Seguimiento', new_seguimiento_path %>

app/views/seguimientos/new.html.erb
<h1>Nuevo Seguimiento</h1>

<%= render 'form', seguimiento: @seguimiento %>

<%= link_to 'Volver', @seguimiento.caso, :class => "button" %>

app/views/seguimientos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fecha:</strong>
  <%= @seguimiento.fecha.localtime.strftime("%d/%m/%Y %H:%M") %>
</p>

<p>
  <strong>Caso:</strong>
  <%= @seguimiento.caso_id %>
</p>

<p>
  <strong>Glosa:</strong>
  <%= @seguimiento.glosa %>
</p>

<p>
  <strong>Documentos:</strong>
  <% if @documentos.empty? %>
    <p>No hay documentos adjuntos</p>
  <% else %>
  <table>
  <thead>  
  <tr>
  <th>Nro.</th>
  <th>Fecha</th>
  <th>Archivo</th>
  <th>Descripción</th>
  <th colspan="3"></th>
  </thead>
  <tbody>
  <% @documentos.each do |documento|%>
  <tr>
  <td><%= documento.id %></td>
  <td><%= documento.fecha.localtime.strftime("%d/%m/%Y %H:%M") %></td>
  <td><a target="_blank" download="<%= documento.archivo %>" href="/docs/<%= documento.adjunto %>"><%= documento.archivo %></a></td>
  <td><%= documento.descripcion.length > 20 ? documento.descripcion.slice(0..20) + "..." : documento.descripcion %></td>
  <td><a class="button" target="_blank" download="<%= documento.archivo %>" href="/docs/<%= documento.adjunto %>">Descargar</a></td>
  <td><%= link_to 'Borrar', documento, method: :delete, data: { confirm: '¿Esta seguro?' } %></td>
  </tr>
  <% end %>
  </tbody>
  </table>
  <% end %>
  <%= link_to 'Agregar nuevo documento', new_caso_seguimiento_documento_path(@seguimiento.caso_id, @seguimiento ), :class => "button" %>  
</p>

<%= link_to 'Volver a caso', caso_path(@seguimiento.caso_id), :class => "button" %>