config/routes.rb
Rails.application.routes.draw do
  get '/', :to => redirect('/casos')
  get '/alumnos/:id/casos', :to => 'alumnos#casos'
  get '/caso/:id/alumno/new', :to => 'alumnos#new'
  resources :faltas
  resources :contravenciones
  resources :sanciones
  resources :documentos
  resources :seguimientos
  resources :castigos
  resources :involucrados
  resources :casos do
    resources :involucrados
  end
  resources :casos do
    resources :involucrados do
      resources :contravenciones
    end
  end
  resources :casos do
    resources :involucrados do
      resources :castigos
    end
  end
  resources :casos do
    resources :seguimientos do
      resources :documentos
    end
  end
  resources :alumnos
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/alumno.rb
class Alumno < ApplicationRecord
  validates :nombre, :presence => true
  validates :rude, :presence => true
  validates :ci, :presence => true
  validates_uniqueness_of :rude, :message => "ya pertenece a otro alumno"
  validates_uniqueness_of :ci, :message => "ya pertenece a otro alumno"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/caso.rb
class Caso < ApplicationRecord
  validates :denunciante, :presence => true
  validates :descripcion, :presence => true
  validates :responsable, :presence => true
end

app/models/castigo.rb
class Castigo < ApplicationRecord
  belongs_to :caso
  belongs_to :sancion
  belongs_to :involucrado
  validates :descripcion, :presence => true
end

app/models/contravencion.rb
class Contravencion < ApplicationRecord
  belongs_to :caso
  belongs_to :falta
  belongs_to :involucrado  
  validates :descripcion, :presence => true
end

app/models/documento.rb
class Documento < ApplicationRecord
  belongs_to :seguimiento
  validates :descripcion, :presence => true
  validates :archivo, :presence => true
end

app/models/falta.rb
class Falta < ApplicationRecord
  def tipo_nombre
    "#{tipo}:#{nombre}"
  end
end

app/models/involucrado.rb
class Involucrado < ApplicationRecord
  belongs_to :caso
  belongs_to :alumno
  validates :participacion, :presence => true
  validates_uniqueness_of :alumno_id, scope: :caso_id, :message => "ya está involucrado en el caso"
end

app/models/sancion.rb
class Sancion < ApplicationRecord
end

app/models/seguimiento.rb
class Seguimiento < ApplicationRecord
  belongs_to :caso
  validates :glosa, :presence => true
end

app/controllers/casos_controller.rb
class CasosController < ApplicationController
  before_action :set_caso, only: %i[ show edit update destroy ]

  # GET /casos or /casos.json
  def index
    @casos = Caso.all
  end

  # GET /casos/1 or /casos/1.json
  def show
    @involucrados = Involucrado.where(caso_id: @caso.id).includes(:alumno) || Hash.new
    @castigos = Castigo.where(caso_id: @caso.id) || Hash.new
    @seguimientos = Seguimiento.where(["caso_id = ?", @caso.id]) || Hash.new
  end

  # GET /casos/new
  def new
    @caso = Caso.new
    @caso.estado = "Abierto"
    @caso.fecha = Time.now
    @involucrados = Hash.new
    @castigos = Hash.new
    @seguimientos = Hash.new
  end

  # GET /casos/1/edit
  def edit
    @involucrados = Involucrado.where(caso_id: @caso.id).includes(:alumno)
    @castigos = Castigo.where(caso_id: @caso.id)
    @seguimientos = Seguimiento.where(caso_id: @caso_id)
  end

  # POST /casos or /casos.json
  def create
    @caso = Caso.new(caso_params)

    respond_to do |format|
      if @caso.save
        format.html { redirect_to @caso, notice: "Caso creado." }
        format.json { render :show, status: :created, location: @caso }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @caso.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /casos/1 or /casos/1.json
  def update
    respond_to do |format|
      if @caso.update(caso_params)
        format.html { redirect_to @caso, notice: "Caso actualizado." }
        format.json { render :show, status: :ok, location: @caso }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @caso.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /casos/1 or /casos/1.json
  def destroy
    begin
      @caso.destroy
    rescue ActiveRecord::InvalidForeignKey => e
      respond_to do |format|
        format.html { redirect_to casos_url, notice: "No puede borrar el Caso hasta no eliminar los involucrados" }
        format.json { rhead :no_content }
      end
      return
    end

    respond_to do |format|
      format.html { redirect_to casos_url, notice: "Caso borrado." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_caso
      @caso = Caso.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def caso_params
      params.require(:caso).permit(:fecha, :estado, :denunciante, :descripcion, :responsable)
    end
end

app/controllers/faltas_controller.rb
class FaltasController < ApplicationController
  before_action :set_falta, only: %i[ show edit update destroy ]

  # GET /faltas or /faltas.json
  def index
    @faltas = Falta.all
  end

  # GET /faltas/1 or /faltas/1.json
  def show
  end

  # GET /faltas/new
  def new
    @falta = Falta.new
  end

  # GET /faltas/1/edit
  def edit
  end

  # POST /faltas or /faltas.json
  def create
    @falta = Falta.new(falta_params)

    respond_to do |format|
      if @falta.save
        format.html { redirect_to @falta, notice: "Falta was successfully created." }
        format.json { render :show, status: :created, location: @falta }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @falta.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /faltas/1 or /faltas/1.json
  def update
    respond_to do |format|
      if @falta.update(falta_params)
        format.html { redirect_to @falta, notice: "Falta was successfully updated." }
        format.json { render :show, status: :ok, location: @falta }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @falta.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /faltas/1 or /faltas/1.json
  def destroy
    @falta.destroy
    respond_to do |format|
      format.html { redirect_to faltas_url, notice: "Falta was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_falta
      @falta = Falta.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def falta_params
      params.require(:falta).permit(:tipo, :nombre, :norma, :posicion, :descripcion, :sanciones)
    end
end

app/helpers/alumnos_helper.rb
module AlumnosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/casos_helper.rb
module CasosHelper
end

app/helpers/castigos_helper.rb
module CastigosHelper
end

app/helpers/contravencions_helper.rb
module ContravencionsHelper
end

app/helpers/documentos_helper.rb
module DocumentosHelper
end

app/helpers/faltas_helper.rb
module FaltasHelper
end

app/helpers/involucrados_helper.rb
module InvolucradosHelper
end

app/helpers/sanciones_helper.rb
module SancionesHelper
end

app/helpers/sancions_helper.rb
module SancionsHelper
end

app/helpers/seguimientos_helper.rb
module SeguimientosHelper
end

app/views/casos/_form.html.erb
<%= form_with(model: caso) do |form| %>
  <% if caso.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(caso.errors.count, "errores") %> evitaron que este caso fuera grabado:</h2>

      <ul>
        <% caso.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :fecha %>
    <%= form.text_field :fecha, :hidden => true %>
    <input value="<%= @caso.fecha.localtime.strftime("%d/%m/%Y %H:%M") %>" readonly>
  </div>

  <div class="field">
    <%= form.label :estado %>
    <%= form.text_field :estado, :readonly => true %>
  </div>

  <div class="field">
    <%= form.label :denunciante %>
    <%= form.text_field :denunciante %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_area :descripcion %>
  </div>

  <div class="field">
    <%= form.label :responsable %>
    <%= form.text_field :responsable %>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/casos/edit.html.erb
<h1>Modificar Caso</h1>

<%= render 'form', caso: @caso %>

<%= link_to 'Lista de casos', casos_path, :class => "button" %>

app/views/casos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Casos</h1>

<table>
  <thead>
    <tr>
      <th>Fecha</th>
      <th>Estado</th>
      <th>Denunciante</th>
      <th>Descripcion</th>
      <th>Responsable</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @casos.each do |caso| %>
      <tr>
        <td><%= caso.fecha.localtime.strftime("%d/%m/%Y %H:%M") %></td>
        <td><%= caso.estado %></td>
        <td><%= caso.denunciante %></td>
        <td><%= caso.descripcion %></td>
        <td><%= caso.responsable %></td>
        <td><%= link_to 'Ver', caso, :class => "button" %></td>
        <td><%= link_to 'Modificar', edit_caso_path(caso), :class => "button" %></td>
        <td><%= link_to 'Borrar', caso, method: :delete, data: { confirm: '¿Esta seguro?' }, :class => "button" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Caso', new_caso_path, :class => "button" %>

app/views/casos/new.html.erb
<h1>Nuevo Caso</h1>

<%= render 'form', caso: @caso %>

<%= link_to 'Lista de casos', casos_path, :class => "button" %>

app/views/casos/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Ficha de caso Nº<%= @caso.id %></h1>

<p>
  <strong>Fecha:</strong>
  <%= @caso.fecha.localtime.strftime("%d/%m/%Y %H:%M") %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @caso.estado %>
</p>
<p>
  <strong>Descripcion:</strong>
  <%= @caso.descripcion %>
</p>
<p>
  <strong>Denunciante:</strong>
  <%= @caso.denunciante %>
</p>

<p>
  <strong>Responsable:</strong>
  <%= @caso.responsable %>
</p>

<p>
  <% if @involucrados.empty? %>
    <p>No hay estudiantes registrados aún</p>
  <% else %>
  <table>
  <caption><strong>Estudiantes involucrados:</strong></caption>
  <thead>
  <tr>
  <th>
    Nombre
  </th>
  <th colspan="3"></th>
  </thead>
  <tbody>
  <% @involucrados.each do |involucrado|%>
  <tr>
  <td><%= involucrado.alumno.nombre %></td>
  <td><%= link_to 'Ver', involucrado, :class => "button" %></td>
  <td><%= link_to 'Editar', edit_involucrado_path(involucrado), :class => "button" %></td>
  <td><%= link_to 'Borrar', involucrado, method: :delete, data: { confirm: '¿Esta seguro?' }, :class => "button" %></td>
  </tr>
  <% end %>
  </tbody>
  </table>
  <% end %>
  <%= link_to 'Agregar alumno involucrado', new_caso_involucrado_path(@caso), :class => "button" %>  
</p>
<p>
  
  <% if @seguimientos.empty? %>
    <p>No hay eventos registrados aún</p>
  <% else %>
  <table>
  <caption><strong>Seguimiento</strong></caption>
  <thead>  
  <tr>
  <th>Nro.</th>
  <th>Fecha</th>
  <th>Glosa</th>
  <th colspan="3"></th>
  </thead>
  <tbody>
  <% @seguimientos.each do |seguimiento|%>
  <tr>
  <td><%= seguimiento.id %></td>
  <td><%= seguimiento.fecha.localtime.strftime("%d/%m/%Y %H:%M") %></td>
  <td><%= seguimiento.glosa.length > 50 ? seguimiento.glosa.slice(0..50) + "..." : seguimiento.glosa %></td>
  <td><%= link_to 'Ver', seguimiento, :class => "button" %></td>
  <td><%= link_to 'Editar', edit_seguimiento_path(seguimiento), :class => "button" %></td>
  <td><%= link_to 'Borrar', seguimiento, method: :delete, data: { confirm: '¿Esta seguro?' }, :class => "button" %></td>
  </tr>
  <% end %>
  </tbody>
  </table>
  <% end %>
  <%= link_to 'Agregar nueva nota/evento/documento', new_caso_seguimiento_path(@caso), :class => "button" %>  
</p>
<%= link_to 'Editar Caso', edit_caso_path(@caso), :class => "button" %> |
<%= link_to 'Lista de casos', casos_path, :class => "button" %>

app/views/faltas/_form.html.erb
<%= form_with(model: falta) do |form| %>
  <% if falta.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(falta.errors.count, "errores") %> evitaron que esta falta fuera grabada:</h2>

      <ul>
        <% falta.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :tipo %>
    <%= form.text_field :tipo %>
  </div>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :norma %>
    <%= form.text_field :norma %>
  </div>

  <div class="field">
    <%= form.label :posicion %>
    <%= form.text_field :posicion %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_area :descripcion %>
  </div>

  <div class="field">
    <%= form.label :sanciones %>
    <%= form.text_area :sanciones %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/faltas/edit.html.erb
<h1>Editing Falta</h1>

<%= render 'form', falta: @falta %>

<%= link_to 'Show', @falta, :class => "button" %> |
<%= link_to 'Back', faltas_path, :class => "button" %>

app/views/faltas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Faltas</h1>

<table>
  <thead>
    <tr>
      <th>Tipo</th>
      <th>Nombre</th>
      <th>Norma</th>
      <th>Posicion</th>
      <th>Descripcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @faltas.each do |falta| %>
      <tr>
        <td><%= falta.tipo %></td>
        <td><%= falta.nombre %></td>
        <td><%= falta.norma %></td>
        <td><%= falta.posicion %></td>
        <td><%= falta.descripcion %></td>
        <td><%= link_to 'Show', falta, :class => "button" %></td>
        <td><%= link_to 'Edit', edit_falta_path(falta), :class => "button" %></td>
        <td><%= link_to 'Destroy', falta, method: :delete, data: { confirm: 'Are you sure?' }, :class => "button" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Falta', new_falta_path %>

app/views/faltas/new.html.erb
<h1>New Falta</h1>

<%= render 'form', falta: @falta %>

<%= link_to 'Back', faltas_path, :class => "button" %>

app/views/faltas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tipo:</strong>
  <%= @falta.tipo %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @falta.nombre %>
</p>

<p>
  <strong>Norma:</strong>
  <%= @falta.norma %>
</p>

<p>
  <strong>Posicion:</strong>
  <%= @falta.posicion %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @falta.descripcion %>
</p>

<p>
  <strong>Sanciones:</strong>
  <%= @falta.sanciones %>
</p>

<%= link_to 'Edit', edit_falta_path(@falta), :class => "button" %> |
<%= link_to 'Back', faltas_path, :class => "button" %>